steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        ls
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'
